name: Sleeper Sync

permissions:
  contents: write

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"


name: Sleeper Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm install

      - name: Fetch Sleeper data
        env:
          SLEEPER_LEAGUE_ID: ${{ vars.SLEEPER_LEAGUE_ID }}
          SLEEPER_WEEK: ${{ vars.SLEEPER_WEEK }}
        run: node scripts/fetch_sleeper.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: update sleeper.json"
            git push
          else
            echo "No changes to commit"
          fi
